In [1]:
import pandas as pd
import numpy as np

In [2]:
fy16_data_path = "Resources/FY16_data.xlsx"
fy16_df = pd.read_excel(fy16_data_path)
fy16_df.head()

,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,REFILE,ORIG_FILE_DATE,ORIG_CASE_NO,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,...,FW_INFO_TRAINING_COMP,FW_INFO_REQ_EXPERIENCE,FW_INFO_ALT_EDU_EXPERIENCE,FW_INFO_REL_OCCUP_EXP,PREPARER_INFO_EMP_COMPLETED,PREPARER_INFO_TITLE,EMPLOYER_DECL_INFO_TITLE,NAICS_US_CODE,NAICS_US_TITLE,PW_Job_Title_9089
0,A-15096-64168,2015-10-01,Withdrawn,2015-05-05,N,NaT,NaN,N,"Think Primary Care, LLC",7101 Mercy Road,...,A,Y,A,A,N,Attorney,Chief Financial Officer,621498,All Other Outpatient Care Centers,Chief Executive
1,A-15273-23908,2015-10-01,Withdrawn,2015-10-01,N,NaT,NaN,N,Shopping & Shopping of Miami Corp,102 SE 1st Street,...,A,Y,A,A,N,President,President,451110,Sporting Goods Stores,Manager
2,A-15063-55943,2015-10-01,Certified-Expired,2015-03-10,NaN,NaT,NaN,N,TEXAS BACK INSTITUTE,6020 WEST PARKER RD,...,A,Y,A,Y,N,Attorney,Director HR,622110,General Medical and Surgical Hospitals,General and Operations Managers
3,A-15258-17757,2015-10-01,Withdrawn,2015-10-01,N,NaT,NaN,N,"SARASOTA LAKEWOOD RANCH VENTURES, LLC",8210 LAKEWOOD RANCH BLVD.,...,A,Y,A,A,N,Attorney,Operating Principal/Broker,53131,Real Estate Property Managers,Market Research Analysts and Marketing Special...
4,A-14212-94282,2015-10-01,Certified-Expired,2014-07-31,NaN,NaT,NaN,N,NATIONS INFO CORPORATION,5951 ENCINA RD #208,...,A,A,A,A,N,Attorney,Human Resources Manager,516110,Internet Publishing and Broadcasting,Marketing Managers

In [3]:
fy16_df.columns

Index(['CASE_NUMBER', 'DECISION_DATE', 'CASE_STATUS', 'CASE_RECEIVED_DATE',
       'REFILE', 'ORIG_FILE_DATE', 'ORIG_CASE_NO', 'SCHD_A_SHEEPHERDER',
       'EMPLOYER_NAME', 'EMPLOYER_ADDRESS_1',
       ...
       'FW_INFO_TRAINING_COMP', 'FW_INFO_REQ_EXPERIENCE',
       'FW_INFO_ALT_EDU_EXPERIENCE', 'FW_INFO_REL_OCCUP_EXP',
       'PREPARER_INFO_EMP_COMPLETED', 'PREPARER_INFO_TITLE',
       'EMPLOYER_DECL_INFO_TITLE', 'NAICS_US_CODE', 'NAICS_US_TITLE',
       'PW_Job_Title_9089'],
      dtype='object', length=125)

In [4]:
# Select the columns that we need
fy16_df2 = fy16_df[['CASE_NUMBER','DECISION_DATE','CASE_STATUS','CASE_RECEIVED_DATE','EMPLOYER_NAME','EMPLOYER_CITY',
                   'EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','EMPLOYER_NUM_EMPLOYEES','AGENT_FIRM_NAME','AGENT_CITY',
                   'AGENT_STATE','PW_SOC_CODE','PW_SOC_TITLE','PW_AMOUNT_9089','WAGE_OFFER_FROM_9089','WAGE_OFFER_UNIT_OF_PAY_9089',
                   'JOB_INFO_WORK_CITY','JOB_INFO_WORK_STATE','JOB_INFO_WORK_POSTAL_CODE','JOB_INFO_JOB_TITLE',
                   'JOB_INFO_EDUCATION','JOB_INFO_EDUCATION_OTHER','FOREIGN_WORKER_INFO_CITY','FOREIGN_WORKER_INFO_STATE',
                   'FW_INFO_POSTAL_CODE','COUNTRY_OF_CITIZENSHIP','FW_INFO_BIRTH_COUNTRY','CLASS_OF_ADMISSION','FOREIGN_WORKER_INFO_EDUCATION','FW_INFO_EDUCATION_OTHER']]
fy16_df2.dtypes

CASE_NUMBER                              object
DECISION_DATE                    datetime64[ns]
CASE_STATUS                              object
CASE_RECEIVED_DATE               datetime64[ns]
EMPLOYER_NAME                            object
EMPLOYER_CITY                            object
EMPLOYER_STATE                           object
EMPLOYER_POSTAL_CODE                     object
EMPLOYER_NUM_EMPLOYEES                  float64
AGENT_FIRM_NAME                          object
AGENT_CITY                               object
AGENT_STATE                              object
PW_SOC_CODE                              object
PW_SOC_TITLE                             object
PW_AMOUNT_9089                          float64
WAGE_OFFER_FROM_9089                    float64
WAGE_OFFER_UNIT_OF_PAY_9089              object
JOB_INFO_WORK_CITY                       object
JOB_INFO_WORK_STATE                      object
JOB_INFO_WORK_POSTAL_CODE                object
JOB_INFO_JOB_TITLE                       object
JOB_INFO_EDUCATION                       object
JOB_INFO_EDUCATION_OTHER                 object
FOREIGN_WORKER_INFO_CITY                 object
FOREIGN_WORKER_INFO_STATE                object
FW_INFO_POSTAL_CODE                      object
COUNTRY_OF_CITIZENSHIP                   object
FW_INFO_BIRTH_COUNTRY                    object
CLASS_OF_ADMISSION                       object
FOREIGN_WORKER_INFO_EDUCATION            object
FW_INFO_EDUCATION_OTHER                  object
dtype: object

In [5]:
# change column to float
fy16_df2.count()

CASE_NUMBER                      126143
DECISION_DATE                    126143
CASE_STATUS                      126143
CASE_RECEIVED_DATE               126143
EMPLOYER_NAME                    126141
EMPLOYER_CITY                    126139
EMPLOYER_STATE                   126131
EMPLOYER_POSTAL_CODE             126136
EMPLOYER_NUM_EMPLOYEES           126105
AGENT_FIRM_NAME                  111186
AGENT_CITY                       113483
AGENT_STATE                      111757
PW_SOC_CODE                      125987
PW_SOC_TITLE                     125987
PW_AMOUNT_9089                   126069
WAGE_OFFER_FROM_9089             126099
WAGE_OFFER_UNIT_OF_PAY_9089      126099
JOB_INFO_WORK_CITY               126108
JOB_INFO_WORK_STATE              126109
JOB_INFO_WORK_POSTAL_CODE        126098
JOB_INFO_JOB_TITLE               126117
JOB_INFO_EDUCATION               126135
JOB_INFO_EDUCATION_OTHER           4028
FOREIGN_WORKER_INFO_CITY         126125
FOREIGN_WORKER_INFO_STATE        115914
FW_INFO_POSTAL_CODE              123995
COUNTRY_OF_CITIZENSHIP           126125
FW_INFO_BIRTH_COUNTRY            126125
CLASS_OF_ADMISSION               117228
FOREIGN_WORKER_INFO_EDUCATION    126122
FW_INFO_EDUCATION_OTHER            5364
dtype: int64

In [6]:
fy16_df2.count()

CASE_NUMBER                      126143
DECISION_DATE                    126143
CASE_STATUS                      126143
CASE_RECEIVED_DATE               126143
EMPLOYER_NAME                    126141
EMPLOYER_CITY                    126139
EMPLOYER_STATE                   126131
EMPLOYER_POSTAL_CODE             126136
EMPLOYER_NUM_EMPLOYEES           126105
AGENT_FIRM_NAME                  111186
AGENT_CITY                       113483
AGENT_STATE                      111757
PW_SOC_CODE                      125987
PW_SOC_TITLE                     125987
PW_AMOUNT_9089                   126069
WAGE_OFFER_FROM_9089             126099
WAGE_OFFER_UNIT_OF_PAY_9089      126099
JOB_INFO_WORK_CITY               126108
JOB_INFO_WORK_STATE              126109
JOB_INFO_WORK_POSTAL_CODE        126098
JOB_INFO_JOB_TITLE               126117
JOB_INFO_EDUCATION               126135
JOB_INFO_EDUCATION_OTHER           4028
FOREIGN_WORKER_INFO_CITY         126125
FOREIGN_WORKER_INFO_STATE        115914
FW_INFO_POSTAL_CODE              123995
COUNTRY_OF_CITIZENSHIP           126125
FW_INFO_BIRTH_COUNTRY            126125
CLASS_OF_ADMISSION               117228
FOREIGN_WORKER_INFO_EDUCATION    126122
FW_INFO_EDUCATION_OTHER            5364
dtype: int64

In [7]:
fy16_df2.to_excel("Resources/FY16_Data_Clean.xlsx")